version: '3'
services:
  plex:
    image: lscr.io/linuxserver/plex
    network_mode: bridge
    ports: 
    - 32400:32400
    environment:
      PGID: "${GID}"
      PUID: "${UID}"
      PLEX_CLAIM: ''
      UMASK: '022'
      VERSION: docker
    volumes:
    - ./config:/config
    - ../movies:/movies
    - ../tvshows:/tvshows
    devices: []
