services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: bridge
    ports: 
    - 32400:32400
    environment:
      PGID: "${PGID}"
      PUID: "${PUID}"
      PLEX_CLAIM: ''
      UMASK: '022'
      VERSION: docker
    volumes:
    - ./config:/config
    - ../movies:/movies
    - ../tvshows:/tvshows
    - ../custom_movies:/custom_movies
    - ../custom_tvshows:/custom_tvshows
    devices: []
