services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    network_mode: bridge
    ports:
    - 1900:1900
    - 7359:7359
    - 8096:8096
    - 8920:8920
    environment:
      PGID: "${PGID}"
      PUID: "${PUID}"
      UMASK: '022'
    volumes:
    - ./config:/config
    - ../movies:/data/movies
    - ../tvshows:/data/shows
    - ../custom_movies:/data/custom_movies
    - ../custom_tvshows:/data/custom_tvshows
    devices: []
